### ISSUE TITLE
issue#1 Clase Point

### ISSUE THREAD

**Issue by asancgom** [asancgom/IWVG-SwC-asancgom#1]
Se pretende ampliar la funcionalidad de dicha clase añadiendo dos funciones que permitan modificar las coordenadas.

    public void setX(int x); 
    public void setY(int y);

Cada función actualizará el valor de esa coordenada por el valor que se informa por parámetro.

**Comment by gmunumel** [comment]
Agregado cambio, subido pull request, hecho merge con rama develop 👍
