### ISSUE TITLE
issue#3 Clase DecimalCollection 

### ISSUE THREAD

**Issue by asancgom** [asancgom/IWVG-SwC-asancgom#3]
Se pretende ampliar la funcionalidad de dicha clase añadiendo la siguiente función:

    public int Means();

Esta función nos devuelve la media de la colección. La media es igual al la división entre la suma de los números de la colección y el número de elementos que tiene la misma.

**Comment by socrtx** [comment]
esta vacio, daina

**Comment by socrtx** [comment]
Terminado
DecimalCollection:means()
DecimalCollectionTest:testMeans()
DecimalCollectionTest:testMeansExceptionIfEmpty()

**Comment by asancgom** [comment]
Reabro el issue por bug detectado por sonar por un cast innecesario en la linea: "return (double) (this.sum() / this.size());" el mensaje exacto es "Remove this unnecessary cast to "double"".

**Comment by socrtx** [comment]
lo contrario que en el otro, hago todo al revés.. 👎
